#lang simply-scheme

(define (make-account balance password)
  (let ((pw-tries-remaining 7))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
               balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (check-attempts)
            (cond ((> pw-tries-remaining 0)
                   (begin (set! pw-tries-remaining (- pw-tries-remaining 1))(error "Wrong password!")))
            (else (call-the-cops))))
    (define (call-the-cops)
      (error "Better run"))
    (define (dispatch pw m)
      (cond ((not (eq? pw password)) (check-attempts))
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    dispatch))